### ISSUE TITLE
the error by bloomfilter

### ISSUE THREAD

**Issue by jonashua2013** [MagnusS/Java-BloomFilter#12]
i have import the bloomfiter in my program

but the program can errors a message

redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Broken pipe (Write failed)
        at redis.clients.jedis.Protocol.sendCommand(Protocol.java:104)
        at redis.clients.jedis.Protocol.sendCommand(Protocol.java:84)
        at redis.clients.jedis.Connection.sendCommand(Connection.java:127)
        at redis.clients.jedis.BinaryClient.setbit(BinaryClient.java:912)
        at redis.clients.jedis.Client.setbit(Client.java:671)
        at redis.clients.jedis.Jedis.setbit(Jedis.java:2555)
        at com.github.wxisme.bloomfilter.bitset.RedisBitSet.set(RedisBitSet.java:70)
        at com.github.wxisme.bloomfilter.common.BloomFilter.add(BloomFilter.java:231)

so i can‘t find the problem

**Comment by jonashua2013** [comment]
Modifying the pool config fixed this issue
